const About = () => {
    return ( 
       <div className='about-content'>
           <h1>About</h1>
           <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia reiciendis perspiciatis aperiam sapiente veritatis, ab magnam accusantium itaque eum molestiae ipsam, eos optio nihil sequi qui. Modi, numquam perspiciatis. Ducimus?Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, eos placeat harum illum ad sit libero qui necessitatibus doloremque minus ipsa voluptatem accusamus natus aspernatur iusto nobis deserunt fuga. Aut expedita quisquam sed natus ratione necessitatibus delectus voluptatem dolore eaque officia vero, esse, illo id dolor porro perferendis? Reprehenderit, quisquam dolorem. Alias et ducimus modi exercitationem magni velit autem. Quo ad, ab animi saepe id ut perspiciatis. Itaque impedit illo consequatur tempora, obcaecati consequuntur architecto accusantium, ducimus facilis voluptas earum ullam dolore iure, sit placeat totam repellendus? Distinctio provident sequi iure nemo nihil, inventore, ipsam eaque saepe vel alias voluptate architecto pariatur ab ullam rerum. Vitae ipsam eligendi nulla consequuntur dicta ut rem incidunt explicabo? Inventore architecto obcaecati aperiam veritatis voluptas reprehenderit velit molestias voluptate. Quae labore aperiam deserunt obcaecati fugit ad quasi ipsam suscipit est sapiente repellat, totam consectetur at quas illo! Aspernatur quis, ab eligendi magni aliquam cum veritatis dolor recusandae dignissimos fuga at suscipit necessitatibus tempore, enim eaque veniam explicabo ad a perspiciatis in mollitia repellendus ipsam nihil? Officiis, quibusdam delectus. Officiis eos asperiores neque veniam aut dicta repellat, eum quibusdam libero aspernatur. Et soluta aut inventore quo sed laborum? Voluptatibus pariatur voluptates fugiat in dolore expedita!.
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium voluptates, consectetur illo assumenda ad illum modi iste ratione alias culpa delectus adipisci quod eveniet, vero ipsam at odio placeat quia atque repellendus deleniti laudantium accusamus! Doloremque esse nam similique voluptatum nesciunt, repellendus eveniet iure maiores. Explicabo porro laboriosam amet aliquid officia. Quam exercitationem nesciunt in corporis sed, incidunt possimus unde, ut consequuntur nobis illum vitae molestiae repellat tempora at pariatur saepe magnam commodi maxime? Quod magnam iusto in. Necessitatibus, dolores. Perferendis error beatae, aut facilis aspernatur ad eveniet iste eos. Maiores eligendi, ratione pariatur recusandae obcaecati quas nisi. Doloremque aliquam, inventore hic ipsa consequuntur deserunt quas vero ad sed id eveniet dolorem corrupti odit vel ut itaque tempore repudiandae ducimus dignissimos! Voluptatibus eveniet a est architecto quasi nisi, cum sint fugiat quo maiores sapiente dolores obcaecati quod ullam ipsa, nobis natus! Maxime deleniti ea asperiores corrupti quidem facilis repellat, quia libero similique voluptatem minus! Unde numquam distinctio et tempora minima velit iste ipsam eaque inventore nihil? Aspernatur minus fugit perferendis enim voluptate repellat dicta pariatur! Sit, porro inventore explicabo perferendis officiis quis exercitationem rem assumenda deserunt consequatur facilis quia maiores optio sunt. Molestiae sunt quaerat totam. Molestias ex accusantium magnam.
           </p>
       </div>
     );
}
 
export default About;